### ISSUE TITLE
it's not compatible with RC.2

### ISSUE THREAD

**Issue by dj-at-work** [tixdo/ng2-modal#1]
Simple, nice and clear, but unfortunately not compatible with RC.2  
The Imports are still in beta style 'angular2/..' -> '@angular/...'
And please check the modal.ts, there are a few lines not compatible to RC.2

**Comment by Skountz** [comment]
@TheNightbear You sould check pending pull request, it's now working !

**Comment by julioaze** [comment]
Hi, update for Angular 2 Final??
Thanks!!!
