### ISSUE TITLE
'loadIntoLocation' does not exist on type 'DynamicComponentLoader'.

### ISSUE THREAD

**Issue by onecib** [tixdo/ng2-modal#2]
Hi there,
got this Error :  error TS2339: Property 'loadIntoLocation' does not exist on type 'DynamicComponentLoader'.

Do I missing anything ? 

Thanks

**Comment by onecib** [comment]
and this one also : 
error TS2314: Generic type 'ComponentRef<C>' requires 1 type argument(s)

**Comment by Skountz** [comment]
Are you using latest version of Angular 2 ?
If the answer is yes, I ran throught the same problem, and I updated modal.ts code to reflect recent changes in Angular API.

**Comment by lee-40square** [comment]
@pokiz if you solved the problem can you post the code please? But yes, loadIntoLocation() was removed from DynamicComponentLoader so line 106 and and I assume 131 will need to be changed in modal.ts although I'm not sure what changes need to be made.

**Comment by ajvorobiev** [comment]
@pokiz can you please share the modified code? Driving me nuts.

**Comment by Skountz** [comment]
Sure, I made a pull request to fit Angular 2 requirements !

**Comment by ajvorobiev** [comment]
@pokiz many thanks. Will try it in a bit and report back.

**Comment by ajvorobiev** [comment]
Thanks @pokiz worked like a charm.
